version: "3.7"

services:
  todo-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    image: todo-app:test
    env_file:
      - .env.test
    ports:
      - 8000:8000
